### PR TITLE
Add support for tilde accent

### PR DESCRIPTION
**Pull request by Phyks**
To be able to write `$tilde x = x / (x_0)$` :)

### CODE REVIEW

**Comment by Phyks** [comment]
Added a synonym for `del` so that `partial_x f` would give the same output. I tend to find it more readable in plaintext for partial derivatives (del refers to much to delta).

Travis-CI does not work, but I don't think I broke it :/

**Comment by Phyks** [comment]
By the way, as we deviate a bit from the AsciiMath spec, not sure if we could easily output a readable grammar from Alex/Happy source codes?

**Comment by Kerl13** [comment]
* About `tilde`: good idea

* About `partial`: I was trying to stick to the asciimath spec (http://asciimath.org/) but I think I am going to slightly get away from it from now. The choice of "del" to refer to LaTeX's `\partial` is actually a good example of bad choice I think they made. Actually, I would be fine with replacing `del` by `partial` rather than just adding an alias.

**Comment by Phyks** [comment]
:+1:

**Pull request merged**
